### ISSUE TITLE
No component found for view with name "ARTShape"

### ISSUE THREAD

**Issue by diegosiao** [nihgwu/react-native-pie#11]
Hi!
I am having the issue attached trying to render a pie defined as below:

                        <View>
                            <Pie
                                radius={50}
                                innerRadius={45}
                                series={[60]}
                                colors={['#f00']}
                                backgroundColor='#ddd' />
                            <View style={styles.gauge}>
                                <Text style={styles.gaugeText}>60%</Text>
                            </View>
                        </View>

I am using React Native 0.55

![simulator screen shot - iphone 6 - 2018-04-18 at 23 17 12](https://user-images.githubusercontent.com/16164884/38967705-b87029c2-435e-11e8-98f7-8c89d28dc899.png)

**Comment by hungdev** [comment]
read docs:https://github.com/nihgwu/react-native-pie#install
step 2: Link the ART library to your ReactNative project (how to link a library). You'll find the React ART library in node_modules/react-native/Libraries/ART/ART.xcodeproj
https://facebook.github.io/react-native/docs/linking-libraries-ios.html#content

**Comment by nihgwu** [comment]
thanks @hungdev

**Comment by vinaygoyal20** [comment]
I was facing this issue for IOS in react-native 60 version.I just add the line below in podfile.
pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'

and then install the pods

**Comment by DruRly** [comment]
> I was facing this issue for IOS in react-native 60 version.I just add the line below in podfile.
> pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
> 
> and then install the pods

This worked after deleting the build and restarting the bundler.
