### ISSUE TITLE
custom pie

### ISSUE THREAD

**Issue by hungdev** [nihgwu/react-native-pie#12]
hi @nihgwu 
thank for your lib. 
i want to create space between lines and border radius lines.
like this. Could you tell me how to do this? Thank you.
<img width="169" alt="screen shot 2018-06-02 at 9 50 41 pm" src="https://user-images.githubusercontent.com/12009276/40877689-2354a038-66af-11e8-81a8-8f34ea445f1c.png">

**Comment by koolkarni** [comment]
did you find the solution for the above question ? and also I wanted to add the glowing color to color



_@hungdev
this is how you can add the black color between arc, but i need rounded edged_ 

  <Pie
               radius={120}
               innerRadius={115}
               series={[58, 2,43, 2]}
               colors={['#00ADF0', '#000', '#ffff', '#000']}
               backgroundColor='#ddd' />

**Comment by hungdev** [comment]
@koolkarni  I don't understand your question. Give me the image you want to do?

**Comment by koolkarni** [comment]
[](url)
![image](https://user-images.githubusercontent.com/16875126/41266054-21fb6e5e-6daa-11e8-9b81-bce7e640d344.png)

@hungdev Did you see my pull request ?

**Comment by hungdev** [comment]
oh, sorry. I didn't find the solution for this.
but Black color is background, you can set props: bacgroundColor: 'black'
