### ISSUE TITLE
Border around pie

### ISSUE THREAD

**Issue by shakedOno** [nihgwu/react-native-pie#14]
Hi and thanks for your awesome work!

I was wondering if I could somehow achieve the following pie:
![screen shot 2018-07-16 at 16 58 24](https://user-images.githubusercontent.com/38178643/42762625-749a7e90-8919-11e8-8e03-c610858100ad.png)

I tried to add a background color in the color of the border, and then have a series like [20, 80] with colors: [blue, white], but the border is really tiny and almost can't be seen. Resulting in:

<img width="44" alt="screen shot 2018-07-16 at 17 01 54" src="https://user-images.githubusercontent.com/38178643/42762819-f8e96bc0-8919-11e8-9ab2-b40a46b558b3.png">

**Comment by nihgwu** [comment]
I think it could be achieved by setting the border color and border radius of the container instead of the pie chart

**Comment by shakedOno** [comment]
Great idea!
It actually worked with border radius and background color of the container.
Thank you!
