### ISSUE TITLE
It shows black rectangle on Android

### ISSUE THREAD

**Issue by risingtalent22** [nihgwu/react-native-pie#21]
![Screenshot_20190703-113540_chylroad](https://user-images.githubusercontent.com/29854456/60561667-eb472e80-9d86-11e9-9acd-7b480996e777.jpg)

My code looks like this and it works fine on iOS.
<Pie
     radius={67}
     series={[30, 70]}
     colors={['#919dfe', '#6274FE']}
/>

**Comment by zgordon01** [comment]
Can you try on the latest version? Closing this issue otherwise please report back if you still see issues
