### ISSUE TITLE
Requirement of Library update for RN0.60+

### ISSUE THREAD

**Issue by SnehalAgrawal** [nihgwu/react-native-pie#22]
Hello Admin, Can you please update for the React Native 0.60+ version.
I have tried different ways to add ART libraries but end the end they are not working with react native's new updated version (React Native 0.60+).

Can you please check and describe any way if any?

**Comment by Preeternal** [comment]
Hi. Did you have problems with IOS? Just add the line below in podfile:
pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'

and then install the pods

But in future we will have a real issue with ART:
Warning: React Native ART has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/art' instead of 'react-native'. See https://github.com/react-native-community/art

Possible, I'll abble to make PR for fix this.

**Comment by Preeternal** [comment]
https://github.com/nihgwu/react-native-pie/pull/23

**Comment by nihgwu** [comment]
landed in v0.6.0

**Comment by Preeternal** [comment]
Seems we need to revert back to v0.5.0
For now auto linking does not work for @react-native-community/art

> landed in v0.6.0

**Comment by nihgwu** [comment]
maybe we should update the document for linking? https://github.com/react-native-community/art#mostly-automatic-linking

**Comment by Preeternal** [comment]
No. My terminal output:
react-native link @react-native-community/art
error Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies. Run CLI with --verbose flag for more details.

**Comment by nihgwu** [comment]
I don't use RN for years, is there a mechanism or `postinstall` to do that automatically?

**Comment by Preeternal** [comment]
Hm.. I don't know. Need to investigate

**Comment by nihgwu** [comment]
What if you install the package explicitly? If it works we can make the art package to peerDependencies instead of dependencies

**Comment by Preeternal** [comment]
Ok. I'll try

**Comment by nihgwu** [comment]
any lucky? I've prepared the needed change

**Comment by Preeternal** [comment]
Any. I don't see the chart with this way too.

**Comment by Preeternal** [comment]
I'll try some different way

**Comment by nihgwu** [comment]
OK, then let's rollback for now

**Comment by Preeternal** [comment]
Yes. Differen't way also loose

**Comment by nihgwu** [comment]
reverted in 0.6.1

**Comment by Preeternal** [comment]
Problem is with @react-native-community/art
I raised PR https://github.com/react-native-community/art/pull/34, but fixed with the PR only Android
I'll rise PR into _react-native-pie_ with some changes. Please merge only after successful implementation in @react-native-community/art needed changes.

**Comment by nihgwu** [comment]
cool, thanks

**Comment by AboutReact** [comment]
Working fine thank you. https://aboutreact.com/react-native-pie-chart/

**Comment by zgordon01** [comment]
@Preeternal @nihgwu 

I tested and everything was working fine, so https://github.com/nihgwu/react-native-pie/pull/24 has been merged which closes this issue
