### ISSUE TITLE
Since v0.2.0: "child keys must be unique" warning

### ISSUE THREAD

**Issue by sirilicious** [nihgwu/react-native-pie#3]
Since the new version 0.2.0, i receive following error warning:

![screen shot 2017-07-12 at 16 22 27](https://user-images.githubusercontent.com/29576073/28122441-7f6f2302-671e-11e7-93a2-b53db355996e.png)

I bet on the modified `key={idx}` property in the `Shape` element.

**Comment by nihgwu** [comment]
I'm calculate the key `key={`${startAngle}-${arcAngle}`}` to avoid using index as key
I think you just pass `series=[x, 0, 0]` to the component, can you provide you related code?

**Comment by sirilicious** [comment]
I'm using the pie as a gauge for percentage between two choices:
```javascript
getPiePercentages(){
   const pA = this.getPercentage(0)/2; // getPercentage(0) returns e.g. 25
   const pB = this.getPercentage(1)/2; // getPercentage(1) returns e.g. 75
   return [pA, pB, pB, pA];
}
```

Which is used as following:
`<Pie series={this.getPiePercentages()} ... />`

**Comment by nihgwu** [comment]
I'll release a new version in next week

**Comment by nihgwu** [comment]
resolved by https://github.com/nihgwu/react-native-pie/commit/86adf51339854ef3dc50df8cef6d12afb9df7b82
