### ISSUE TITLE
Version 1.0.0 Deployment

### ISSUE THREAD

**Issue by zgordon01** [nihgwu/react-native-pie#31]
@nihgwu is it possible that we get version 1.0 deployed to npm? My team is going to consume it soon.

**Comment by zgordon01** [comment]
@milindagrawal

**Comment by nihgwu** [comment]
@zgordon01 I'll release a new version soon, sorry for the late response

**Comment by zgordon01** [comment]
No problem. We have a week or so before it's required. Feel free to close this issue once it's deployed.

**Comment by nihgwu** [comment]
published

**Comment by milindagrawal** [comment]
@nihgwu Thanks, this really helps..!!
