### ISSUE TITLE
Module `@react-native-community/art` does not exist in the Haste module map

### ISSUE THREAD

**Issue by uendar** [nihgwu/react-native-pie#38]
Unable to resolve module `@react-native-community/art` from `...\HS-Hemes\node_modules\react-native-pie\src\Pie.js`: Module `@react-native-community/art` does not exist in the Haste module map

How do we solve this. the version of modules is    "react-native-pie": "^1.1.2",

**Comment by milindagrawal** [comment]
You will have to explicitly install `@react-native-community/art` in your project to resolve this issue.

**Comment by milindagrawal** [comment]
@zgordon01 We will have to update this in `Readme`
