### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by hyochan** [nihgwu/react-native-pie#5]
You library worked fined in react-native 0.47 but when I upgraded to 0.48.4 today, below error appeared any idea?

<img width="351" alt="2017-10-05 7 03 36" src="https://user-images.githubusercontent.com/27461460/31221830-f16d6170-a9ff-11e7-9064-7352baff9c19.png">

**Comment by hyochan** [comment]
Sorry maybe it is not your problem.

**Comment by nihgwu** [comment]
maybe it's 😁

**Comment by nihgwu** [comment]
I just released a new version

**Comment by hyochan** [comment]
Thank you.
