### ISSUE TITLE
Values on series

### ISSUE THREAD

**Issue by ellatuquero** [nihgwu/react-native-pie#6]
Sir I have a dynamic value for the pie [40,0,0,0] for the colors ['red', 'lime', 'blue', 'yellow', 'green']. Here was the output 
![capture _2018-01-08-14-05-16](https://user-images.githubusercontent.com/33537635/34660429-399e8e02-f47d-11e7-93c9-71225279462e.png)

Sir how can I fill the whole circle just like my values above. Thank you in advance!

**Comment by nihgwu** [comment]
try `backgroundColor`

**Comment by ellatuquero** [comment]
already solve it sir thank you!
