### ISSUE TITLE
Android series issue

### ISSUE THREAD

**Issue by ruchi1906** [nihgwu/react-native-pie#9]
<Pie
radius={80}
innerRadius={60}
series={[31,24,16,355,18,1,165]}
colors={['#f00', '#0f0', '#00f', '#ff0','green','blue','red']} />

passing values like this doesn't reflect in piechart shows only a constant color

**Comment by ruchi1906** [comment]
![screen shot 2018-01-19 at 12 31 31 pm](https://user-images.githubusercontent.com/32831173/35138495-da457772-fd14-11e7-8b8f-993278d5e2ff.png)

**Comment by hungdev** [comment]
you are wrong series props. 
series percentage array

**Comment by nihgwu** [comment]
thanks @hungdev
